[environments.dev]
_github="git@github.com:devshopify/Shokz-CA-2.0.git"
_branch=""
project_desc=""
domain="https://ca.shokz.com"
theme = ""
store = "aftershokz-canada.myshopify.com"
port = 9292
preview_key=""