[environments.dev]
_github="git@github.com:devshopify/shokz_de.git"
_branch=""
project_desc=""
domain="https://de.shokz.com"
theme = ""
store = "aftershokz-de.myshopify.com"
port = 9292
preview_key=""
preview_path=""
