[environments.dev]
_github="git@github.com:shokz-shopify/Shokz-US-2.0.git"
_branch=""
project_desc=""
domain="https://shokz.com"
theme = ""
store = "aftershokz-com.myshopify.com"
port = 9292
preview_key=""